@file:JvmName("Constants")
@file:JvmMultifileClass

package io.github.kingg22.ktorgen.model

const val KTORG_GENERATED_COMMENT = "Generated by KtorgGen"

const val KTORG_GENERATED_FILE_COMMENT = "This file was generated by KtorgGen. Do not edit manually!"
