@file:JvmName("Constants")
@file:JvmMultifileClass

package io.github.kingg22.ktorgen.model

// need to be consistent with annotations constant
const val KTORGEN_DEFAULT_VALUE = "__DEFAULT__"

const val KTORG_GENERATED_COMMENT = "Generated by KtorgGen"

const val KTORG_GENERATED_FILE_COMMENT = "This file was generated by KtorgGen. Do not edit manually!"

// required imports
const val KTOR_CLIENT_SET_BODY = "io.ktor.client.request.setBody"
const val KTOR_CLIENT_HEADERS = "io.ktor.client.request.headers"
const val KTOR_CLIENT_ATTRIBUTE_KEY = "io.ktor.util.AttributeKey"
const val KTOR_HTTP_METHOD = "io.ktor.http.HttpMethod"
const val KTOR_ENCODE_URL_PATH = "io.ktor.http.encodeURLPath"
const val KTOR_CLIENT_FORM_DATA_CONTENT = "io.ktor.client.request.forms.FormDataContent"
const val KTOR_CLIENT_MULTI_PART_FORM_DATA_CONTENT = "io.ktor.client.request.forms.MultiPartFormDataContent"
const val KTOR_CLIENT_FORM_DATA = "io.ktor.client.request.forms.formData"
const val KTOR_PARAMETERS = "io.ktor.http.Parameters"
const val KTOR_CLIENT_HTTP_REQUEST_BUILDER = "io.ktor.client.request.HttpRequestBuilder"
const val KTOR_CLIENT_PARAMETER = "io.ktor.client.request.parameter"
const val KTOR_URL_BUILDER = "io.ktor.http.URLBuilder"
const val KTOR_URL_TAKE_FROM = "io.ktor.http.takeFrom"
const val KTOR_DECODE_URL_QUERY = "io.ktor.http.decodeURLQueryComponent"
