@file:JvmName("Constants")
@file:JvmMultifileClass

package io.github.kingg22.ktorgen.model

import com.squareup.kotlinpoet.ClassName

// need to be consistent with annotations constant
const val KTORGEN_DEFAULT_VALUE = "__DEFAULT__"

const val KTORG_GENERATED_COMMENT = "Generated by KtorGen"
const val KTORG_GENERATED_FILE_COMMENT = "This file was generated by KtorGen. Do not edit manually!"

/**
 * Regex for matching URL path parameters.
 * Example: `{id}` or `{[id]}`
 */
val UrlPathRegex = "\\{([^}]+)}".toRegex()

const val KTOR_CLIENT_REQUEST_PACKAGE = "io.ktor.client.request"

// required imports
const val KTOR_CONTENT_TYPE = "io.ktor.http.ContentType"
const val KTOR_CONTENT_TYPE_ADD = "io.ktor.http.contentType"
const val KTOR_CLIENT_SET_BODY = "$KTOR_CLIENT_REQUEST_PACKAGE.setBody"
const val KTOR_CLIENT_HEADERS = "$KTOR_CLIENT_REQUEST_PACKAGE.headers"
const val KTOR_CLIENT_COOKIE = "$KTOR_CLIENT_REQUEST_PACKAGE.cookie"
const val KTOR_CLIENT_ATTRIBUTE_KEY = "io.ktor.util.AttributeKey"
const val KTOR_GMT_DATE = "io.ktor.util.date.GMTDate"
const val KTOR_HTTP_METHOD = "io.ktor.http.HttpMethod"
const val KTOR_ENCODE_URL_PATH = "io.ktor.http.encodeURLPath"
const val KTOR_CLIENT_FORM_DATA_CONTENT = "$KTOR_CLIENT_REQUEST_PACKAGE.forms.FormDataContent"
const val KTOR_CLIENT_MULTI_PART_FORM_DATA_CONTENT = "$KTOR_CLIENT_REQUEST_PACKAGE.forms.MultiPartFormDataContent"
const val KTOR_CLIENT_FORM_DATA = "$KTOR_CLIENT_REQUEST_PACKAGE.forms.formData"
const val KTOR_CLIENT_PART_DATA = "io.ktor.http.content.PartData"
const val KTOR_PARAMETERS = "io.ktor.http.Parameters"

val HttpClientClassName = ClassName("io.ktor.client", "HttpClient")
val HttpRequestBuilderTypeName = ClassName(KTOR_CLIENT_REQUEST_PACKAGE, "HttpRequestBuilder")
private val HttpRequestTypeName = ClassName(KTOR_CLIENT_REQUEST_PACKAGE, "HttpRequest")
private val HttpRequestDataTypeName = ClassName(KTOR_CLIENT_REQUEST_PACKAGE, "HttpRequestData")

// see https://api.ktor.io/ktor-client/ktor-client-core/io.ktor.client.request/-http-request-builder/index.html?query=class%20HttpRequestBuilder%20:%20HttpMessageBuilder#-1196439924%2FFunctions%2F-1897681819
val VALID_HTTP_REQUEST_TAKE_FROM = setOf(HttpRequestBuilderTypeName, HttpRequestTypeName, HttpRequestDataTypeName)
